# Configuration for ticket intents based on all 8 system categories
INTENT_RULES = {
    "vpn": {
        "vpn_connection_issue": [
            "قطع",
            "وصل",
            "ارور",
            "error",
            "disconnect",
            "connectivity",
            "وی_پی_ان",
        ],
        "vpn_request": ["اکانت", "جدید", "دسترسی", "create", "new", "account"],
    },
    "email": {
        "email_access_issue": [
            "ورود",
            "پسورد",
            "رمز",
            "لاگین",
            "login",
            "password",
            "sign-in",
        ],
        "email_quota_issue": [
            "حجم",
            "پر",
            "فضا",
            "گیگابایت",
            "quota",
            "full",
            "space",
            "storage",
        ],
    },
    "network": {
        "network_drop": [
            "قطع",
            "وصل",
            "اینترنت",
            "وای_فای",
            "کابل",
            "internet",
            "wifi",
            "disconnect",
        ],
        "network_speed": ["کند", "کندی", "سرعت", "slow", "speed", "ping"],
    },
    "printer": {
        "printer_error": ["خراب", "گیر", "کاغذ", "ارور", "printer", "paper", "jam"],
        "print_queue": [
            "صف",
            "چاپ",
            "پرینت",
            "تونر",
            "کارتریج",
            "print",
            "queue",
            "toner",
        ],
    },
    "account": {
        "account_lock": [
            "قفل",
            "بسته",
            "رمز",
            "پسورد",
            "فراموش",
            "lock",
            "password",
            "reset",
            "سامانه",
        ],
        "account_creation": ["ساخت", "جدید", "تعریف", "کاربر", "user", "create", "new"],
    },
    "hardware": {
        "hardware_failure": [
            "خراب",
            "سوخته",
            "روشن",
            "مانیتور",
            "کیس",
            "broken",
            "hardware",
            "monitor",
            "power",
        ],
        "hardware_request": [
            "درخواست",
            "موس",
            "کیبورد",
            "تجهیزات",
            "جدید",
            "request",
            "mouse",
            "keyboard",
            "hardware",
        ],
    },
    "software": {
        "software_install": [
            "نصب",
            "دانلود",
            "بروزرسانی",
            "آپدیت",
            "install",
            "update",
            "download",
        ],
        "software_error": [
            "کرش",
            "خطا",
            "ارور",
            "بسته",
            "error",
            "crash",
            "close",
            "license",
        ],
    },
    "permission": {
        "permission_denied": [
            "خطا",
            "دسترسی",
            "پوشه",
            "فایل",
            "ارور",
            "access",
            "denied",
            "permission",
            "folder",
        ],
        "permission_request": [
            "درخواست",
            "مجوز",
            "اشتراک",
            "پوشه",
            "request",
            "share",
            "folder",
            "allow",
        ],
    },
}
